# Generated by Django 5.1.1 on 2024-10-08 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_gigglecatalogue_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gigglecatalogue',
            name='giggleLevel',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
