# Generated by Django 5.1.1 on 2024-10-08 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_gigglecatalogue_gigglelevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gigglecatalogue',
            name='giggleLevel',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
